image: Visual Studio 2019
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

for:
# configuration for "master" branch, build in Release mode
-
  branches:
    only:
      - master
  configuration: Release
# configuration for "development" branch, build in Debug mode
-
  branches:
    only:
      - development
  configuration: Debug
# "fall back" configuration for all other branches
# no "branches" section defined
configuration: Debug
before_build:
  - cmd: nuget install NUnit.Console -Version 3.11.1 -OutputDirectory testrunner
  - cmd: nuget install NUnit.Runners -Version 3.11.1 -OutputDirectory testrunner
  - cmd: nuget sources add -name devexpress -source %DEVEXPRESS_API%
  - cmd: nuget restore -verbosity quiet
  - cmd: choco install opencover.portable
  - cmd: choco install codecov

build:
  project: CDP4-CE.sln
  verbosity: quiet
test:
  assemblies:
    only:
      - '**\bin\$(configuration)\*.Tests.dll'
  categories:
    except:
      - WebServicesDependent
      - AppVeyorExclusion
after_test:
  - OpenCover.Console.exe -register:user -target:".\testrunner\NUnit.ConsoleRunner.3.11.1\tools/\nunit3-console.exe" -targetargs:"cdp4ime-tests.nunit /exclude:WebServicesDependent,AppVeyorExclusion" -filter:"-[*.Tests*]*" -output:".\cdp4ime_coverage.xml" -oldstyle -log:Error
  - codecov -f "cdp4ime_coverage.xml" -t %CODECOV_TOKEN%
notifications:
  - provider: Email
    to:
      - cdp_devs@rheagroup.com
